"""Generate Note-fenced.sublime-syntax. Run from the package root."""

# (context suffix, info-string tags, embedded scope, meta.language suffix)
LANGS = [
    ("bat", "bat|batch|cmd|dosbatch", "source.dosbatch", "dosbatch"),
    ("c", "c|h", "source.c", "c"),
    ("c++", r"c\+\+|cpp|cxx|cc|hpp", "source.c++", "c++"),
    ("clojure", "clojure|clj|cljs", "source.clojure", "clojure"),
    ("coffee", "coffee|coffeescript", "source.coffee", "coffee"),
    ("csharp", "cs|csharp|c#", "source.cs", "cs"),
    ("css", "css", "source.css", "css"),
    ("diff", "diff|patch", "source.diff", "diff"),
    ("erlang", "erlang|erl", "source.erlang", "erlang"),
    ("go", "go|golang", "source.go", "go"),
    ("haskell", "haskell|hs", "source.haskell", "haskell"),
    ("html", "html|htm|xhtml", "text.html.basic", "html"),
    ("java", "java", "source.java", "java"),
    ("js", "js|javascript|mjs|cjs|node", "source.js", "javascript"),
    ("json", "json|jsonc|json5", "source.json", "json"),
    ("jsx", "jsx", "source.jsx", "jsx"),
    ("latex", "latex", "text.tex.latex", "tex.latex"),
    ("less", "less", "source.less", "less"),
    ("lisp", "lisp|elisp", "source.lisp", "lisp"),
    ("lua", "lua", "source.lua", "lua"),
    ("makefile", "makefile|make|mk", "source.makefile", "makefile"),
    ("markdown", "markdown|md", "text.html.markdown", "markdown"),
    ("matlab", "matlab", "source.matlab", "matlab"),
    ("obj-c", "objective-c|objc", "source.objc", "objc"),
    ("perl", "perl|pl", "source.perl", "perl"),
    ("php", "php", "source.php", "php"),
    ("powershell", "powershell|pwsh|ps1|posh", "source.powershell", "powershell"),
    ("python", "python|py|py3", "source.python", "python"),
    ("r", "r", "source.r", "r"),
    ("regexp", "regexp|regex", "source.regexp", "regexp"),
    ("ruby", "ruby|rb", "source.ruby", "ruby"),
    ("rust", "rust|rs", "source.rust", "rust"),
    ("sass", "sass", "source.sass", "sass"),
    ("scala", "scala", "source.scala", "scala"),
    ("scss", "scss", "source.scss", "scss"),
    ("shell", "sh|shell|bash|console|shell-script", "source.shell.bash", "shell"),
    ("sql", "sql|mysql|psql|postgres|postgresql", "source.sql", "sql"),
    ("tex", "tex", "text.tex", "tex"),
    ("toml", "toml", "source.toml", "toml"),
    ("ts", "ts|typescript", "source.ts", "typescript"),
    ("tsx", "tsx", "source.tsx", "tsx"),
    ("xml", "xml|svg|xsl|xslt|plist", "text.xml", "xml"),
    ("yaml", "yaml|yml", "source.yaml", "yaml"),
    ("zsh", "zsh", "source.shell.zsh", "zsh"),
]

HEADER = r"""%YAML 1.2
---
# Fenced code blocks for PlainNotes. Generated by scripts/gen_fenced.py -- edit that, not this.
#
# Languages are pulled in with `embed` + `escape` rather than `include`, so the
# closing fence always ends the block no matter what state the embedded syntax
# is in (an unclosed `{`, string, template literal, ...).
name: "-"
scope: text.html.markdown.note.fenced
hidden: true

variables:
  # 1: indentation, 2: fence, 3: language, 4: rest of the info string
  fence_open: '(?:^|\G)([ \t]*)([`~]{3,})[ \t]*'
  fence_info: '(?=[ \t{]|$)[ \t]*([^\n]*?)[ \t]*$\n?'
  fence_close: '^[ \t]*(\2)[ \t]*$\n?'

contexts:
  main:
    - include: fenced-code-blocks

  fenced-code-blocks:
"""

BLOCK = """  fenced-{name}:
    - match: '{{{{fence_open}}}}((?i:{tags})){{{{fence_info}}}}'
      captures:
        0: markup.raw.block.markdown markup.raw.block.fenced.markdown
        2: punctuation.definition.raw.block.fenced.markdown
        3: meta.definition.language.raw.block.fenced.markdown
        4: meta.definition.language.raw.block.fenced.markdown
      embed: scope:{scope}
      embed_scope: markup.raw.block.markdown markup.raw.block.fenced.markdown meta.language.{meta}
      escape: '{{{{fence_close}}}}'
      escape_captures:
        0: markup.raw.block.markdown markup.raw.block.fenced.markdown
        1: punctuation.definition.raw.block.fenced.markdown
"""

UNDEFINED = r"""  fenced-undefined:
    - match: '{{fence_open}}([^\n]*?)[ \t]*$\n?'
      captures:
        0: markup.raw.block.markdown markup.raw.block.fenced.markdown
        2: punctuation.definition.raw.block.fenced.markdown
        3: meta.definition.language.raw.block.fenced.markdown
      push:
        - meta_scope: markup.raw.block.markdown markup.raw.block.fenced.markdown
        - match: '{{fence_close}}'
          captures:
            1: punctuation.definition.raw.block.fenced.markdown
          pop: true
"""


def main():
    out = [HEADER]
    out += [f"    - include: fenced-{name}\n" for name, *_ in LANGS]
    out.append("    - include: fenced-undefined\n\n")
    out += [BLOCK.format(name=n, tags=t, scope=s, meta=m) + "\n" for n, t, s, m in LANGS]
    out.append(UNDEFINED)
    with open("Note-fenced.sublime-syntax", "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(out))


if __name__ == "__main__":
    main()
